# Generated by Django 5.1.3 on 2024-12-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindestbestand', models.IntegerField(verbose_name='Mindestbestand')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('liefereinheit', models.CharField(max_length=50, verbose_name='Liefereinheit')),
                ('bemerkung', models.TextField(blank=True, null=True, verbose_name='Bemerkung')),
                ('ekpreis', models.IntegerField(verbose_name='Einkaufspreis in Cent')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.AlterField(
            model_name='lieferung',
            name='lieferant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bestellung.lieferant', verbose_name='Lieferant'),
        ),
    ]
