# Generated by Django 5.1.3 on 2024-12-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0002_artikel_alter_lieferung_lieferant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagerplatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.IntegerField(verbose_name='Bestand')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestellung.artikel', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Lagerplatz',
                'verbose_name_plural': 'Lagerplätze',
            },
        ),
        migrations.CreateModel(
            name='Lieferposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verkaufspreis', models.IntegerField(verbose_name='Verkaufspreis in €-Cent')),
                ('menge', models.IntegerField(verbose_name='Anzahl')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestellung.artikel', verbose_name='Artikel')),
                ('lieferung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestellung.lieferung', verbose_name='Lieferung')),
            ],
            options={
                'verbose_name': 'Lieferposition',
                'verbose_name_plural': 'Lieferposition',
            },
        ),
    ]
